Blog/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'comments/create'

  get 'comments/destroy'

  resources :users
  resources :posts do
	resources :comments
  end

   
   root :to => 'posts#index'

end

Blog/app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
end

Blog/app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
end

Blog/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

Blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!, except: [:show, :index, :create]
  def create
	@post = Post.find(params[:post_id])
	@comment = @post.comments.build(params.require(:comment).permit(:text))
	@comment.save
	redirect_to @post
  end
	
  def destroy
     @comment = Comment.find(params[:id])
     @comment.destroy
     redirect_to @comment.post
  end
end

Blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, except: [:show, :index]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    
    respond_to do |format|
      format.html
      format.xml {render :xml => @posts}
      format.atom
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :text)
    end
end

Blog/app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
  end

  def index
  end
end

Blog/app/helpers/application_helper.rb
module ApplicationHelper
end

Blog/app/helpers/comments_helper.rb
module CommentsHelper
end

Blog/app/helpers/posts_helper.rb
module PostsHelper
end

Blog/app/helpers/user_helper.rb
module UserHelper
end

Blog/app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

Blog/app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

Blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= auto_discovery_link_tag :atom, "posts.atom"%>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<% if user_signed_in? %>
    <span>Здравствуйте, <%= current_user.email %></span>
    <%= link_to 'Выйти', destroy_user_session_path, :method => :delete %>
<% else %>
    <%= link_to 'Войти', new_user_session_path %> или <%= link_to 'Зарегистрироваться', new_user_registration_path %>
<% end %>

<%= yield %>

</body>
</html>

Blog/app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, "Заголовок" %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :text, "Сообщение" %><br>
    <%= f.text_area :text %>
  </div>
  <div class="actions">
    <%= f.submit "Сохранить" %>
  </div>
<% end %>

Blog/app/views/posts/edit.html.erb
<h1>Редактирование почта</h1>

<%= render 'form' %>

<%= link_to 'Показать', @post %> |
<%= link_to 'Назад', posts_path %>

Blog/app/views/posts/index.html.erb
<h1>Добро пожаловать в мой блог</h1>
<% @posts.each do |post|%>
	<h2><%= link_to post.title, post %></h2>
	<p>
		<%= truncate post.text%>
	</p>
	<p>
		<%= time_ago_in_words post.created_at%> назад
	</p>
<% end %>
<p>

    <%= link_to "Новое сообщение", new_post_path%>

</p>

Blog/app/views/posts/new.html.erb
<h1>Новый пост</h1>

<%= render 'form' %>

<%= link_to 'Назад', posts_path %>

Blog/app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p>
<%= @post.text %>
</p>

<h2>Комментарии</h2>
<% @post.comments.each do |comment| %>
<h4>
	<%= time_ago_in_words comment.created_at %> назад
</h4>
<p>
	<%= comment.text%>
</p>
	<%= link_to "Удалить комментарий", [@post, comment], :method => :delete, :confirm => "Вы уверены?"%>
<%end%>

<%= form_for [@post, @post.comments.build] do |f| %>
	<%= f.text_area :text, :size => "40x10"%>
	<br>
	<%= f.submit "Отправить комментарий"%>
<%end%>

<%= link_to "Назад", posts_path%>
|
<%= link_to "Редактировать", edit_post_path(@post)%>
|
<%= link_to "Удалить", @post, :method => :delete, :confirm => 'Вы уверены?'%>

Blog/app/views/user/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>

Blog/app/views/user/show.html.erb
<h1>User#show</h1>
<p>Find me in app/views/user/show.html.erb</p>